language: go

env:
  - GO111MODULE=on

go:
- 1.12.x
- 1.11.x


script:
  - golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic


after_success:
  - bash <(curl -s https://codecov.io/bash)
